version: "3"

# https://mindsers.blog/post/https-using-nginx-certbot-docker/
# or https://gilyes.com/docker-nginx-letsencrypt/

services:
  webserver:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - nginx_conf:/etc/nginx/conf.d/:rw
      - certbot_www:/var/certbot/:rw
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/nginx/ssl/:rw
      - certbot_conf:/etc/letsencrypt/:rw

volumes:
  nginx_conf:
  certbot_www:
  certbot_conf:
