version: "3"

# https://mindsers.blog/post/https-using-nginx-certbot-docker/
# or https://gilyes.com/docker-nginx-letsencrypt/

services:
  webserver:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www:/var/certbot/:rw
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw